# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'sinatra'
gem 'nsq-ruby'

# Development
gem 'dotenv'

# Testing
gem 'rspec'
gem 'webmock'
gem 'rack-test'
