# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'sinatra'

gem 'rspec'
gem 'rack-test'

gem 'nsq-ruby'

gem 'redis'

gem 'dotenv'

gem 'foreman'
gem 'rake'

