require ::File.expand_path('../config/environment', __FILE__)
require 'rake'

namespace :listener do
  desc "Start listeners based on ENV variable"
  task :start do
    threads = Array.new(ENV['NUMBER_OF_LISTENERS'].to_i) do
      Thread
        .new { Services::Loop.call }
        .tap { |thread| thread.abort_on_exception = true }
    end
    threads.each(&:join)
  end
end
