require ::File.expand_path('../config/environment', __FILE__)
require 'rake'

namespace :listener do
  desc "Start the NSQ listenr"
  task :start do
    Listener.call
  end

  desc "Populate the database with dummy data by running db/seeds.rb"
  task :seed do
    require APP_ROOT.join('db', 'seeds.rb')
  end
end
